server:
  port: 8056
  compression:
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: "dd/MM/yyyy"
    time-zone: ${app.settings.timezone}
    serialization:
      write_dates_as_timestamps: false
  output:
    ansi:
      enabled: always

token:
  signer:
    secret: ${TOKEN_SIGNER_SECRET}

app:
  settings:
    timezone: ${APP_SETTINGS_TIMEZONE}

icarus:
  pae:
    url: ${ICARUS_PAE_URL}
  server:
    url: ${ICARUS_SERVER_URL}
